[package]
name = "wav2mono"
version = "1.2.2"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4"
eframe = "0.33"

[build-dependencies]
winres = "0.1"
